version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: moneybee-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - moneybee-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  customer-service:
    build:
      context: .
      dockerfile: src/Services/MoneyBee.Customer/MoneyBee.Customer.API/Dockerfile
    container_name: customer-service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=moneybee-db;Port=5432;Database=MoneyBee_CustomerDb;Username=postgres;
      - Authentication__ApiKey=MoneyBeeSecret123
      - ExternalServices__KycUrl=http://external-kyc:8082
    depends_on:
      db:
        condition: service_healthy
    networks:
      - moneybee-network

  transfer-service:
    build:
      context: .
      dockerfile: src/Services/MoneyBee.Transfer/MoneyBee.Transfer.API/Dockerfile
    container_name: transfer-service
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=moneybee-db;Port=5432;Database=MoneyBee_TransferDb;Username=postgres;
      - Authentication__ApiKey=MoneyBeeSecret123
      - ExternalServices__CustomerUrl=http://customer-service:8080
      - ExternalServices__FraudUrl=http://external-fraud:8081
      - ExternalServices__ExchangeRateUrl=http://external-exchange:8083
    depends_on:
      db:
        condition: service_healthy
      customer-service:
        condition: service_started
    networks:
      - moneybee-network

  external-fraud:
    image: bpnpay/fraud-service
    container_name: external-fraud
    ports:
      - "8081:8081"
    networks:
      - moneybee-network

  external-kyc:
    image: bpnpay/kyc-service
    container_name: external-kyc
    ports:
    - "8082:8082"
    networks:
      - moneybee-network

  external-exchange:
    image: bpnpay/exchange-rate-service
    container_name: external-exchange
    ports:
     - "8083:8083"
    networks:
      - moneybee-network

networks:
  moneybee-network:
    driver: bridge