// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyBee.Customer.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneyBee.Customer.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20260207012227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneyBee.Customer.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerId1");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e11111e9-2ba9-473a-a40f-e38cb54f9b35"),
                            AccountNumber = "TR990000100012345678901001",
                            Balance = 10000.00m,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 2, 7, 1, 22, 27, 609, DateTimeKind.Utc).AddTicks(670),
                            Currency = "TRY",
                            CustomerId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("e22222e9-2ba9-473a-a40f-e38cb54f9b35"),
                            AccountNumber = "TR990000100012345678901002",
                            Balance = 500.00m,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 2, 7, 1, 22, 27, 609, DateTimeKind.Utc).AddTicks(670),
                            Currency = "USD",
                            CustomerId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("MoneyBee.Customer.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKycVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            BirthDate = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 2, 7, 1, 22, 27, 609, DateTimeKind.Utc).AddTicks(610),
                            Email = "samet@moneybee.com",
                            FirstName = "Samet Can",
                            IsDeleted = false,
                            IsKycVerified = true,
                            LastName = "Çelik",
                            NationalId = "12345678901",
                            PhoneNumber = "5551112233",
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            BirthDate = new DateTime(1988, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 2, 7, 1, 22, 27, 609, DateTimeKind.Utc).AddTicks(610),
                            Email = "viewer@moneybee.com",
                            FirstName = "Viewer",
                            IsDeleted = false,
                            IsKycVerified = false,
                            LastName = "User",
                            NationalId = "98765432109",
                            PhoneNumber = "5559998877",
                            Status = 1,
                            TaxNumber = "9998887766",
                            Type = 2
                        });
                });

            modelBuilder.Entity("MoneyBee.Customer.Domain.Entities.CustomerLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DailyTotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastTransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerLimits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f11111e9-2ba9-473a-a40f-e38cb54f9b35"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 2, 7, 1, 22, 27, 609, DateTimeKind.Utc).AddTicks(690),
                            CustomerId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            DailyTotalAmount = 10000.00m,
                            IsDeleted = false,
                            LastTransactionDate = new DateTime(2026, 2, 7, 1, 22, 27, 609, DateTimeKind.Utc).AddTicks(690)
                        },
                        new
                        {
                            Id = new Guid("f22222e9-2ba9-473a-a40f-e38cb54f9b35"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 2, 7, 1, 22, 27, 609, DateTimeKind.Utc).AddTicks(690),
                            CustomerId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            DailyTotalAmount = 0.00m,
                            IsDeleted = false,
                            LastTransactionDate = new DateTime(2026, 2, 7, 1, 22, 27, 609, DateTimeKind.Utc).AddTicks(690)
                        });
                });

            modelBuilder.Entity("MoneyBee.Customer.Domain.Entities.Account", b =>
                {
                    b.HasOne("MoneyBee.Customer.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyBee.Customer.Domain.Entities.Customer", null)
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId1");
                });

            modelBuilder.Entity("MoneyBee.Customer.Domain.Entities.CustomerLimit", b =>
                {
                    b.HasOne("MoneyBee.Customer.Domain.Entities.Customer", "Customer")
                        .WithOne("CustomerLimit")
                        .HasForeignKey("MoneyBee.Customer.Domain.Entities.CustomerLimit", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MoneyBee.Customer.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("CustomerLimit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
