// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyBee.Transfer.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneyBee.Transfer.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(TransferDbContext))]
    partial class TransferDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneyBee.Transfer.Domain.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AmountInTry")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReceiverCustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderCustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("TransactionCode")
                        .IsUnique();

                    b.ToTable("Transfers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b11111e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Amount = 100.00m,
                            AmountInTry = 3300.00m,
                            ApprovedDate = new DateTime(2026, 2, 7, 1, 30, 13, 209, DateTimeKind.Utc).AddTicks(730),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 2, 7, 1, 30, 13, 209, DateTimeKind.Utc).AddTicks(730),
                            Currency = "USD",
                            Fee = 1.50m,
                            IsDeleted = false,
                            ReceiverCustomerId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            SenderCustomerId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Status = "COMPLETED",
                            TransactionCode = "TX-USD-2026-001"
                        },
                        new
                        {
                            Id = new Guid("c22222e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Amount = 500.00m,
                            AmountInTry = 500.00m,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 2, 7, 1, 30, 13, 209, DateTimeKind.Utc).AddTicks(740),
                            Currency = "TRY",
                            Fee = 5.00m,
                            IsDeleted = false,
                            ReceiverCustomerId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            SenderCustomerId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            Status = "PENDING",
                            TransactionCode = "TX-TRY-2026-002"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
